// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/image/image.proto

package image

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PullRequest struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Repo                 string   `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullRequest) Reset()         { *m = PullRequest{} }
func (m *PullRequest) String() string { return proto.CompactTextString(m) }
func (*PullRequest) ProtoMessage()    {}
func (*PullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1601d38c23c01d, []int{0}
}

func (m *PullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequest.Unmarshal(m, b)
}
func (m *PullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequest.Marshal(b, m, deterministic)
}
func (m *PullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequest.Merge(m, src)
}
func (m *PullRequest) XXX_Size() int {
	return xxx_messageInfo_PullRequest.Size(m)
}
func (m *PullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequest proto.InternalMessageInfo

func (m *PullRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *PullRequest) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *PullRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type PullResponse struct {
	Results              []*Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PullResponse) Reset()         { *m = PullResponse{} }
func (m *PullResponse) String() string { return proto.CompactTextString(m) }
func (*PullResponse) ProtoMessage()    {}
func (*PullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1601d38c23c01d, []int{1}
}

func (m *PullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullResponse.Unmarshal(m, b)
}
func (m *PullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullResponse.Marshal(b, m, deterministic)
}
func (m *PullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullResponse.Merge(m, src)
}
func (m *PullResponse) XXX_Size() int {
	return xxx_messageInfo_PullResponse.Size(m)
}
func (m *PullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullResponse proto.InternalMessageInfo

func (m *PullResponse) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

type Result struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Message              []string `protobuf:"bytes,2,rep,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1601d38c23c01d, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Result) GetMessage() []string {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*PullRequest)(nil), "PullRequest")
	proto.RegisterType((*PullResponse)(nil), "PullResponse")
	proto.RegisterType((*Result)(nil), "Result")
}

func init() { proto.RegisterFile("pkg/image/image.proto", fileDescriptor_ea1601d38c23c01d) }

var fileDescriptor_ea1601d38c23c01d = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x41, 0x4a, 0xc6, 0x30,
	0x10, 0x85, 0xc9, 0x9f, 0xd2, 0xd2, 0x69, 0x05, 0x09, 0x08, 0xc1, 0x55, 0xad, 0x9b, 0xae, 0x22,
	0xb6, 0xde, 0x41, 0xdc, 0x49, 0x3c, 0x41, 0x95, 0x21, 0x16, 0x5b, 0x13, 0x33, 0xa9, 0xe7, 0x97,
	0x24, 0x54, 0xba, 0x09, 0xef, 0x7d, 0x8b, 0x97, 0xf9, 0xe0, 0xc6, 0x7d, 0x99, 0x87, 0x65, 0x9b,
	0x0d, 0xe6, 0x57, 0x39, 0x6f, 0x83, 0xed, 0x9f, 0xa1, 0x79, 0xdd, 0xd7, 0x55, 0xe3, 0xcf, 0x8e,
	0x14, 0x84, 0x80, 0xe2, 0xd3, 0x52, 0x90, 0xac, 0x63, 0x43, 0xad, 0x53, 0x8e, 0xcc, 0xa3, 0xb3,
	0xf2, 0x92, 0x59, 0xcc, 0xe2, 0x1a, 0x78, 0x98, 0x8d, 0xe4, 0x09, 0xc5, 0xd8, 0x3f, 0x42, 0x9b,
	0x87, 0xc8, 0xd9, 0x6f, 0x42, 0x71, 0x07, 0x95, 0x47, 0xda, 0xd7, 0x40, 0x92, 0x75, 0x7c, 0x68,
	0xc6, 0x4a, 0xe9, 0xd4, 0xf5, 0xc1, 0xfb, 0x27, 0x28, 0x33, 0x3a, 0xe6, 0xd8, 0xff, 0x9c, 0x90,
	0x50, 0x6d, 0x48, 0x34, 0x1b, 0x94, 0x97, 0x8e, 0x0f, 0xb5, 0x3e, 0xea, 0x38, 0x41, 0xfb, 0x12,
	0x05, 0xde, 0xd0, 0xff, 0x2e, 0x1f, 0x28, 0xee, 0xa1, 0x88, 0x1f, 0x8b, 0x56, 0x9d, 0x44, 0x6e,
	0xaf, 0xd4, 0xf9, 0x9a, 0xf7, 0x32, 0xd9, 0x4e, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x04, 0x46,
	0x4a, 0x38, 0x06, 0x01, 0x00, 0x00,
}
