// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/image/image.proto

package image

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PullRequest struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Repo                 string   `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullRequest) Reset()         { *m = PullRequest{} }
func (m *PullRequest) String() string { return proto.CompactTextString(m) }
func (*PullRequest) ProtoMessage()    {}
func (*PullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1601d38c23c01d, []int{0}
}

func (m *PullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequest.Unmarshal(m, b)
}
func (m *PullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequest.Marshal(b, m, deterministic)
}
func (m *PullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequest.Merge(m, src)
}
func (m *PullRequest) XXX_Size() int {
	return xxx_messageInfo_PullRequest.Size(m)
}
func (m *PullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequest proto.InternalMessageInfo

func (m *PullRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *PullRequest) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *PullRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type PullResponse struct {
	Results              []*Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PullResponse) Reset()         { *m = PullResponse{} }
func (m *PullResponse) String() string { return proto.CompactTextString(m) }
func (*PullResponse) ProtoMessage()    {}
func (*PullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1601d38c23c01d, []int{1}
}

func (m *PullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullResponse.Unmarshal(m, b)
}
func (m *PullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullResponse.Marshal(b, m, deterministic)
}
func (m *PullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullResponse.Merge(m, src)
}
func (m *PullResponse) XXX_Size() int {
	return xxx_messageInfo_PullResponse.Size(m)
}
func (m *PullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullResponse proto.InternalMessageInfo

func (m *PullResponse) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

type Result struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Message              []string `protobuf:"bytes,2,rep,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea1601d38c23c01d, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Result) GetMessage() []string {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*PullRequest)(nil), "PullRequest")
	proto.RegisterType((*PullResponse)(nil), "PullResponse")
	proto.RegisterType((*Result)(nil), "Result")
}

func init() { proto.RegisterFile("pkg/image/image.proto", fileDescriptor_ea1601d38c23c01d) }

var fileDescriptor_ea1601d38c23c01d = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xc1, 0x4a, 0xc5, 0x30,
	0x10, 0x45, 0x4d, 0x53, 0x5a, 0x3a, 0xad, 0x20, 0x01, 0x21, 0xb8, 0xaa, 0x01, 0xa1, 0xab, 0x14,
	0xab, 0xff, 0x20, 0xee, 0x24, 0x7f, 0x50, 0x61, 0x88, 0x62, 0x6b, 0xf2, 0x3a, 0xe9, 0xff, 0x3f,
	0x92, 0xd0, 0x47, 0x37, 0xe1, 0xde, 0xb3, 0xb8, 0x99, 0x03, 0x8f, 0xfe, 0xcf, 0x8e, 0xbf, 0xeb,
	0x6c, 0x31, 0xbf, 0xda, 0x6f, 0x2e, 0x38, 0xf5, 0x01, 0xed, 0xd7, 0xbe, 0x2c, 0x06, 0x2f, 0x3b,
	0x52, 0x10, 0x02, 0xca, 0x1f, 0x47, 0x41, 0xb2, 0x9e, 0x0d, 0x8d, 0x49, 0x39, 0xb2, 0x0d, 0xbd,
	0x93, 0x45, 0x66, 0x31, 0x8b, 0x07, 0xe0, 0x61, 0xb6, 0x92, 0x27, 0x14, 0xa3, 0x7a, 0x85, 0x2e,
	0x0f, 0x91, 0x77, 0xff, 0x84, 0xe2, 0x19, 0xea, 0x0d, 0x69, 0x5f, 0x02, 0x49, 0xd6, 0xf3, 0xa1,
	0x9d, 0x6a, 0x6d, 0x52, 0x37, 0x07, 0x57, 0xef, 0x50, 0x65, 0x74, 0xcc, 0xb1, 0xdb, 0x9c, 0x90,
	0x50, 0xaf, 0x48, 0x34, 0x5b, 0x94, 0x45, 0xcf, 0x87, 0xc6, 0x1c, 0x75, 0x1a, 0xa1, 0xfa, 0x8c,
	0x02, 0x24, 0x5e, 0xa0, 0x8c, 0x5f, 0x8a, 0x4e, 0x9f, 0x14, 0x9e, 0xee, 0xf5, 0xf9, 0x0e, 0x75,
	0xf7, 0x5d, 0x25, 0xd3, 0xb7, 0x6b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xba, 0x00, 0xc7, 0xea, 0x02,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ImagesClient is the client API for Images service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ImagesClient interface {
	Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*PullResponse, error)
}

type imagesClient struct {
	cc *grpc.ClientConn
}

func NewImagesClient(cc *grpc.ClientConn) ImagesClient {
	return &imagesClient{cc}
}

func (c *imagesClient) Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*PullResponse, error) {
	out := new(PullResponse)
	err := c.cc.Invoke(ctx, "/Images/Pull", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImagesServer is the server API for Images service.
type ImagesServer interface {
	Pull(context.Context, *PullRequest) (*PullResponse, error)
}

func RegisterImagesServer(s *grpc.Server, srv ImagesServer) {
	s.RegisterService(&_Images_serviceDesc, srv)
}

func _Images_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Images/Pull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).Pull(ctx, req.(*PullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Images_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Images",
	HandlerType: (*ImagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pull",
			Handler:    _Images_Pull_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/image/image.proto",
}
