workspace:
  base: /go
  path: src/github.com/softleader/captain-kube

pipeline:
  build:
    image: golang:alpine
    commands:
      - echo "nameserver 8.8.8.8" >> /etc/resolv.conf
      - apk update && apk --no-cache add git && rm -rf /var/cache/apk/* 
      - go get github.com/goreleaser/goreleaser
      - go get
      - goreleaser --rm-dist
    volumes:
      - /root/.config/goreleaser:/root/.config/goreleaser
    when:
      event: tag

  publish:
    image: plugins/docker
    registry: hub.softleader.com.tw
    insecure: true
    dockerfile: Dockerfile.drone
    repo: "hub.softleader.com.tw/${DRONE_REPO_NAME}"
    tags: "${DRONE_TAG=latest}"
    when:
      event: tag

  # slack:
  #   image: plugins/slack
  #   channel: rd
  #   webhook: https://hooks.slack.com/services/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
  #   when:
  #     status: [ success, failure ]
  #     local: false
