FROM golang:alpine
MAINTAINER softleader.com.tw

RUN apk update && \
	apk --no-cache add bash make git && \
	rm -rf /var/cache/apk/*

COPY installer.sh.drone /installer.sh

WORKDIR $GOPATH/src/github.com/softleader/captain-kube/

COPY . .

ENTRYPOINT ["/bin/sh", "/installer.sh"]