[[constraint]]
  name = "github.com/docker/docker"
  version = "17.05.0-ce-rc3"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.17.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  source = "github.com/dnephin/cobra"
  version = "1.5.1"

[[constraint]]
  name = "github.com/mholt/archiver"
  revision = "master"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.2.0"
