fullnameOverride: false
nameOverride: false

nginx: 
  image: nginx
  tag: alpine
  pullPolicy: IfNotPresent

captainKube:
  image: softleader/captain-kube
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  path: /captain-kube

volume:
  hostPath: /changeit

nodePort:
  enabled: false
  port: 30080