---
- name: Pulling images
  shell: docker pull {{ item.Registry }}/{{ item.Name }}
  loop: "{{ images }}"
  tags:
    - pull

- name: Tagging images
  shell: docker tag {{ item.Registry}}/{{ item.Name }} {{ registry }}/{{ item.Name }}
  loop: "{{ retag_images }}"
  tags:
    - retag

- name: Pushing images
  shell: docker push {{ registry }}/{{ item.Name }}
  loop: "{{ retag_images }}"
  tags:
    - retag