---
- name: upload charts
  copy:
    src: "{{ chart_path }}"
    dest: "{{ workdir.path }}/{{ chart }}"
  tags:
    - always

- name: bx pr login
  shell: bx pr login -a https://{{ inventory_hostname }}:8443 --skip-ssl-validation -u {{ kubectl_user }} -p '{{ kubectl_pass }}' -c '{{ icp_account }}'
  tags:
    - icp

- name: bx pr load charts
  shell: bx pr load-helm-chart --archive {{ workdir.path }}/{{ chart }}
  tags:
    - icp

- name: install charts
  shell: helm install {{ workdir.path }}/{{ chart }} -n {{ namespace }}
  tags:
    - helm