defaultValue:
  captainUrl: localhost:30051
  tags:
  - icp
  namespace: default
  version:
  verbose: false
  sourceRegistry: changeit
  registry:
registryAuth:
  username: dev
  password: sleader
tiller:
  endpoint: k8s.master.vip:8443
  username: admin
  password: admin
  account: icp Account
  skipSslValidation: true
