apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "captain-kube.captain" . }}
  labels:
    app: {{ template "captain-kube.captain" . }}
    chart: {{ template "captain-kube.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "captain-kube.captain" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "captain-kube.captain" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "captain-kube.captain" . }}
          image: "{{ .Values.captain.image }}:{{ .Values.captain.tag }}"
          imagePullPolicy: {{ .Values.captain.pullPolicy }}
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.captain.port }}"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.captain.port }}"]
            initialDelaySeconds: 10
          envFrom:
            - configMapRef:
                name: {{ template "captain-kube.config" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "captain-kube.captain" . }}
  labels:
    app: {{ template "captain-kube.captain" . }}
    chart: {{ template "captain-kube.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - name: {{ template "captain-kube.captain" . }}
      protocol: TCP
      port: {{ .Values.captain.port }}
      nodePort: {{ .Values.captain.port }}
  selector:
    app: {{ template "captain-kube.captain" . }}
    release: {{ .Release.Name }}