---
- name: Porting images
  hosts: porter
  roles:
    - porting

- name: Synchronising images to production nodes
  hosts: production
  roles:
    - syncing

- name: Drafting a release
  hosts: production
  roles:
    - workdir
    - kubectl
    - helm-chart