---
- name: Preparing Materials
  hosts: porter
  roles:
    - porting

- name: Synchronising to Staging Nodes
  hosts: staging
  roles:
    - syncing

- name: Staging a Helm Charts
  hosts: staging
  roles:
    - kubectl
    - workdir
    - helm-chart