version: '3.4'
services:
  capui:
    image: softleader/capui:{changeit}ENV_GIN_MODE
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "--active-ctx {changeit}"
    environment:
      - ENV_GIN_MODE=release
      - CAPUI_CTX_{changeit}=--endpoint {changeit} --retag-to {changeit} --retag-from hub.softleader.com.tw
    healthcheck:
      test: ["CMD", "curl", "--fail", "127.0.0.1:8080", "-H", "X-Health-Check: 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - 8080:8080