version: '3'
services:
  capui:
    image: softleader/capui:{changeit}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "--active-ctx choose-a-context"
    environment:
      - CAPUI_CTX_named-a-context=--endpoint changeit --retag-to changeit --retag-from hub.softleader.com.tw
      - CAPUI_CTX_another-context=...
    ports:
      - 8080:8080