// Code generated by protoc-gen-go. DO NOT EDIT.
// source: caplet.proto

// 依照 https://cloud.google.com/apis/design/naming_convention 規範

package captainkube_v2

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PullImageRequest struct {
	Images               []*Image      `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	RegistryAuth         *RegistryAuth `protobuf:"bytes,2,opt,name=registry_auth,json=registryAuth,proto3" json:"registry_auth,omitempty"`
	Verbose              bool          `protobuf:"varint,3,opt,name=verbose,proto3" json:"verbose,omitempty"`
	Color                bool          `protobuf:"varint,4,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PullImageRequest) Reset()         { *m = PullImageRequest{} }
func (m *PullImageRequest) String() string { return proto.CompactTextString(m) }
func (*PullImageRequest) ProtoMessage()    {}
func (*PullImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_219179cd1e560aae, []int{0}
}

func (m *PullImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullImageRequest.Unmarshal(m, b)
}
func (m *PullImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullImageRequest.Marshal(b, m, deterministic)
}
func (m *PullImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullImageRequest.Merge(m, src)
}
func (m *PullImageRequest) XXX_Size() int {
	return xxx_messageInfo_PullImageRequest.Size(m)
}
func (m *PullImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullImageRequest proto.InternalMessageInfo

func (m *PullImageRequest) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *PullImageRequest) GetRegistryAuth() *RegistryAuth {
	if m != nil {
		return m.RegistryAuth
	}
	return nil
}

func (m *PullImageRequest) GetVerbose() bool {
	if m != nil {
		return m.Verbose
	}
	return false
}

func (m *PullImageRequest) GetColor() bool {
	if m != nil {
		return m.Color
	}
	return false
}

func init() {
	proto.RegisterType((*PullImageRequest)(nil), "softleader.captainkube.v2.PullImageRequest")
}

func init() { proto.RegisterFile("caplet.proto", fileDescriptor_219179cd1e560aae) }

var fileDescriptor_219179cd1e560aae = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xcb, 0x4a, 0xf3, 0x40,
	0x14, 0x6e, 0xfe, 0xfc, 0x6d, 0xed, 0x49, 0x2b, 0x72, 0x70, 0x11, 0xbb, 0x0a, 0x05, 0xb1, 0x2a,
	0x04, 0x89, 0x1b, 0xb7, 0xda, 0x95, 0xa0, 0x50, 0xb2, 0x10, 0x14, 0x44, 0x26, 0xf1, 0x98, 0x0e,
	0x4d, 0x32, 0x71, 0x2e, 0x15, 0x1f, 0xc2, 0x17, 0xf3, 0xa9, 0xa4, 0x49, 0x5a, 0x54, 0x68, 0x90,
	0xee, 0xe6, 0x3b, 0x7c, 0x97, 0x73, 0x19, 0xe8, 0xc7, 0xac, 0x48, 0x49, 0xfb, 0x85, 0x14, 0x5a,
	0xe0, 0x81, 0x12, 0x2f, 0x3a, 0x25, 0xf6, 0x4c, 0xd2, 0x8f, 0x59, 0xa1, 0x19, 0xcf, 0xe7, 0x26,
	0x22, 0x7f, 0x11, 0x0c, 0x1d, 0x9e, 0xb1, 0x84, 0x2a, 0xde, 0xb0, 0x97, 0xa9, 0xa4, 0x7e, 0x3a,
	0x85, 0x34, 0xf9, 0xba, 0x2e, 0x33, 0x5e, 0x3f, 0x07, 0x0b, 0x92, 0x8a, 0x8b, 0xbc, 0x82, 0xa3,
	0x4f, 0x0b, 0xf6, 0xa6, 0x26, 0x4d, 0xaf, 0x97, 0x2e, 0x21, 0xbd, 0x1a, 0x52, 0x1a, 0x2f, 0xa0,
	0x53, 0xba, 0x2a, 0xd7, 0xf2, 0xec, 0xb1, 0x13, 0x78, 0xfe, 0xc6, 0x7c, 0xbf, 0x12, 0xd6, 0x7c,
	0xbc, 0x81, 0x81, 0xa4, 0x84, 0x2b, 0x2d, 0xdf, 0x9f, 0x98, 0xd1, 0x33, 0xf7, 0x9f, 0x67, 0x8d,
	0x9d, 0xe0, 0xa8, 0xc1, 0x20, 0xac, 0xf9, 0x97, 0x46, 0xcf, 0xc2, 0xbe, 0xfc, 0x86, 0xd0, 0x85,
	0xee, 0x82, 0x64, 0x24, 0x14, 0xb9, 0xb6, 0x67, 0x8d, 0x77, 0xc2, 0x15, 0xc4, 0x7d, 0x68, 0xc7,
	0x22, 0x15, 0xd2, 0xfd, 0x5f, 0xd6, 0x2b, 0x10, 0x7c, 0xd8, 0xd0, 0x99, 0x94, 0x7b, 0x43, 0x82,
	0xde, 0x7a, 0x2c, 0x3c, 0x6d, 0x88, 0xff, 0x3d, 0xfc, 0xb0, 0xa9, 0xd7, 0xc9, 0xcc, 0xe4, 0xf3,
	0x5b, 0x52, 0x8a, 0x25, 0x34, 0x6a, 0x9d, 0x59, 0xf8, 0x08, 0xed, 0xe9, 0x72, 0xcf, 0xd8, 0xa4,
	0x2a, 0x19, 0x5b, 0xd9, 0x47, 0xd0, 0xbd, 0xab, 0xce, 0x85, 0xc7, 0x0d, 0xba, 0x9a, 0xb3, 0x8a,
	0x38, 0xf9, 0x0b, 0x55, 0x15, 0x22, 0x57, 0x34, 0x6a, 0xe1, 0x3d, 0xd8, 0x61, 0xc6, 0xf1, 0xb0,
	0xe9, 0x44, 0x19, 0xdf, 0xa6, 0xfd, 0xab, 0x00, 0x3c, 0xfd, 0xe6, 0xc7, 0x22, 0xdb, 0x2c, 0x7a,
	0xd8, 0xfd, 0x89, 0xa3, 0x4e, 0xf9, 0x2f, 0xcf, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xae,
	0xb6, 0xce, 0x01, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CapletClient is the client API for Caplet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CapletClient interface {
	PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (Caplet_PullImageClient, error)
	Prune(ctx context.Context, in *PruneRequest, opts ...grpc.CallOption) (Caplet_PruneClient, error)
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	Rmi(ctx context.Context, in *RmiRequest, opts ...grpc.CallOption) (Caplet_RmiClient, error)
}

type capletClient struct {
	cc *grpc.ClientConn
}

func NewCapletClient(cc *grpc.ClientConn) CapletClient {
	return &capletClient{cc}
}

func (c *capletClient) PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (Caplet_PullImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Caplet_serviceDesc.Streams[0], "/softleader.captainkube.v2.Caplet/PullImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &capletPullImageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Caplet_PullImageClient interface {
	Recv() (*ChunkMessage, error)
	grpc.ClientStream
}

type capletPullImageClient struct {
	grpc.ClientStream
}

func (x *capletPullImageClient) Recv() (*ChunkMessage, error) {
	m := new(ChunkMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *capletClient) Prune(ctx context.Context, in *PruneRequest, opts ...grpc.CallOption) (Caplet_PruneClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Caplet_serviceDesc.Streams[1], "/softleader.captainkube.v2.Caplet/Prune", opts...)
	if err != nil {
		return nil, err
	}
	x := &capletPruneClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Caplet_PruneClient interface {
	Recv() (*ChunkMessage, error)
	grpc.ClientStream
}

type capletPruneClient struct {
	grpc.ClientStream
}

func (x *capletPruneClient) Recv() (*ChunkMessage, error) {
	m := new(ChunkMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *capletClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/softleader.captainkube.v2.Caplet/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capletClient) Rmi(ctx context.Context, in *RmiRequest, opts ...grpc.CallOption) (Caplet_RmiClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Caplet_serviceDesc.Streams[2], "/softleader.captainkube.v2.Caplet/Rmi", opts...)
	if err != nil {
		return nil, err
	}
	x := &capletRmiClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Caplet_RmiClient interface {
	Recv() (*ChunkMessage, error)
	grpc.ClientStream
}

type capletRmiClient struct {
	grpc.ClientStream
}

func (x *capletRmiClient) Recv() (*ChunkMessage, error) {
	m := new(ChunkMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CapletServer is the server API for Caplet service.
type CapletServer interface {
	PullImage(*PullImageRequest, Caplet_PullImageServer) error
	Prune(*PruneRequest, Caplet_PruneServer) error
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	Rmi(*RmiRequest, Caplet_RmiServer) error
}

func RegisterCapletServer(s *grpc.Server, srv CapletServer) {
	s.RegisterService(&_Caplet_serviceDesc, srv)
}

func _Caplet_PullImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CapletServer).PullImage(m, &capletPullImageServer{stream})
}

type Caplet_PullImageServer interface {
	Send(*ChunkMessage) error
	grpc.ServerStream
}

type capletPullImageServer struct {
	grpc.ServerStream
}

func (x *capletPullImageServer) Send(m *ChunkMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _Caplet_Prune_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PruneRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CapletServer).Prune(m, &capletPruneServer{stream})
}

type Caplet_PruneServer interface {
	Send(*ChunkMessage) error
	grpc.ServerStream
}

type capletPruneServer struct {
	grpc.ServerStream
}

func (x *capletPruneServer) Send(m *ChunkMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _Caplet_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapletServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/softleader.captainkube.v2.Caplet/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapletServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Caplet_Rmi_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RmiRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CapletServer).Rmi(m, &capletRmiServer{stream})
}

type Caplet_RmiServer interface {
	Send(*ChunkMessage) error
	grpc.ServerStream
}

type capletRmiServer struct {
	grpc.ServerStream
}

func (x *capletRmiServer) Send(m *ChunkMessage) error {
	return x.ServerStream.SendMsg(m)
}

var _Caplet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "softleader.captainkube.v2.Caplet",
	HandlerType: (*CapletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Caplet_Version_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullImage",
			Handler:       _Caplet_PullImage_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Prune",
			Handler:       _Caplet_Prune_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Rmi",
			Handler:       _Caplet_Rmi_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "caplet.proto",
}
