// Code generated by protoc-gen-go. DO NOT EDIT.
// source: caplet.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PullImageRequest struct {
	Images               []*Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullImageRequest) Reset()         { *m = PullImageRequest{} }
func (m *PullImageRequest) String() string { return proto.CompactTextString(m) }
func (*PullImageRequest) ProtoMessage()    {}
func (*PullImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_219179cd1e560aae, []int{0}
}

func (m *PullImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullImageRequest.Unmarshal(m, b)
}
func (m *PullImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullImageRequest.Marshal(b, m, deterministic)
}
func (m *PullImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullImageRequest.Merge(m, src)
}
func (m *PullImageRequest) XXX_Size() int {
	return xxx_messageInfo_PullImageRequest.Size(m)
}
func (m *PullImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullImageRequest proto.InternalMessageInfo

func (m *PullImageRequest) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

type Image struct {
	Host                 string        `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Repo                 string        `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Tag                  string        `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	RegistryAuth         *RegistryAuth `protobuf:"bytes,4,opt,name=registryAuth,proto3" json:"registryAuth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_219179cd1e560aae, []int{1}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Image) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *Image) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Image) GetRegistryAuth() *RegistryAuth {
	if m != nil {
		return m.RegistryAuth
	}
	return nil
}

type RegistryAuth struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistryAuth) Reset()         { *m = RegistryAuth{} }
func (m *RegistryAuth) String() string { return proto.CompactTextString(m) }
func (*RegistryAuth) ProtoMessage()    {}
func (*RegistryAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_219179cd1e560aae, []int{2}
}

func (m *RegistryAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistryAuth.Unmarshal(m, b)
}
func (m *RegistryAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistryAuth.Marshal(b, m, deterministic)
}
func (m *RegistryAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistryAuth.Merge(m, src)
}
func (m *RegistryAuth) XXX_Size() int {
	return xxx_messageInfo_RegistryAuth.Size(m)
}
func (m *RegistryAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistryAuth.DiscardUnknown(m)
}

var xxx_messageInfo_RegistryAuth proto.InternalMessageInfo

func (m *RegistryAuth) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegistryAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type PullImageResponse struct {
	Message              []byte   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullImageResponse) Reset()         { *m = PullImageResponse{} }
func (m *PullImageResponse) String() string { return proto.CompactTextString(m) }
func (*PullImageResponse) ProtoMessage()    {}
func (*PullImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_219179cd1e560aae, []int{3}
}

func (m *PullImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullImageResponse.Unmarshal(m, b)
}
func (m *PullImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullImageResponse.Marshal(b, m, deterministic)
}
func (m *PullImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullImageResponse.Merge(m, src)
}
func (m *PullImageResponse) XXX_Size() int {
	return xxx_messageInfo_PullImageResponse.Size(m)
}
func (m *PullImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullImageResponse proto.InternalMessageInfo

func (m *PullImageResponse) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*PullImageRequest)(nil), "proto.PullImageRequest")
	proto.RegisterType((*Image)(nil), "proto.Image")
	proto.RegisterType((*RegistryAuth)(nil), "proto.RegistryAuth")
	proto.RegisterType((*PullImageResponse)(nil), "proto.PullImageResponse")
}

func init() { proto.RegisterFile("caplet.proto", fileDescriptor_219179cd1e560aae) }

var fileDescriptor_219179cd1e560aae = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x8d, 0x69, 0xa3, 0x9d, 0xe6, 0x50, 0xc7, 0x83, 0x4b, 0x4f, 0x21, 0x78, 0xc8, 0xc5,
	0x22, 0xf1, 0xa0, 0x57, 0x15, 0x04, 0xc1, 0x83, 0xe4, 0x1b, 0xac, 0x3a, 0xa4, 0x85, 0xa4, 0xbb,
	0xee, 0x6c, 0x10, 0xfd, 0xf4, 0xb2, 0x7f, 0x0c, 0x51, 0x4f, 0x99, 0xf7, 0x7e, 0x33, 0x99, 0xb7,
	0x03, 0xf9, 0xab, 0xd4, 0x1d, 0xd9, 0x8d, 0x36, 0xca, 0x2a, 0x9c, 0xfb, 0x4f, 0x79, 0x03, 0xab,
	0xe7, 0xa1, 0xeb, 0x1e, 0x7b, 0xd9, 0x52, 0x43, 0xef, 0x03, 0xb1, 0xc5, 0x73, 0xc8, 0x76, 0x4e,
	0xb3, 0x48, 0x8a, 0xb4, 0x5a, 0xd6, 0x79, 0x18, 0xd9, 0x84, 0xa6, 0xc8, 0xca, 0x2f, 0x98, 0x7b,
	0x03, 0x11, 0x66, 0x5b, 0xc5, 0x56, 0x24, 0x45, 0x52, 0x2d, 0x1a, 0x5f, 0x3b, 0xcf, 0x90, 0x56,
	0xe2, 0x30, 0x78, 0xae, 0xc6, 0x15, 0xa4, 0x56, 0xb6, 0x22, 0xf5, 0x96, 0x2b, 0xf1, 0x1a, 0x72,
	0x43, 0xed, 0x8e, 0xad, 0xf9, 0xbc, 0x1d, 0xec, 0x56, 0xcc, 0x8a, 0xa4, 0x5a, 0xd6, 0xa7, 0x71,
	0x5d, 0x33, 0x41, 0xcd, 0xaf, 0xc6, 0xf2, 0x01, 0xf2, 0x29, 0xc5, 0x35, 0x1c, 0x0f, 0x4c, 0x66,
	0x2f, 0x7b, 0x8a, 0x31, 0x46, 0xed, 0x98, 0x96, 0xcc, 0x1f, 0xca, 0xbc, 0xc5, 0x38, 0xa3, 0x2e,
	0x2f, 0xe0, 0x64, 0xf2, 0x7a, 0xd6, 0x6a, 0xcf, 0x84, 0x02, 0x8e, 0x7a, 0x62, 0x96, 0x6d, 0xf8,
	0x57, 0xde, 0xfc, 0xc8, 0xfa, 0x09, 0xb2, 0x7b, 0x7f, 0x43, 0xbc, 0x83, 0xc5, 0x38, 0x88, 0x67,
	0x31, 0xf0, 0xdf, 0x43, 0xae, 0xc5, 0x7f, 0x10, 0x76, 0x94, 0x07, 0x97, 0xc9, 0x4b, 0xe6, 0xe1,
	0xd5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xbd, 0xe1, 0x61, 0x98, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CapletClient is the client API for Caplet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CapletClient interface {
	PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (Caplet_PullImageClient, error)
}

type capletClient struct {
	cc *grpc.ClientConn
}

func NewCapletClient(cc *grpc.ClientConn) CapletClient {
	return &capletClient{cc}
}

func (c *capletClient) PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (Caplet_PullImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Caplet_serviceDesc.Streams[0], "/proto.Caplet/PullImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &capletPullImageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Caplet_PullImageClient interface {
	Recv() (*PullImageResponse, error)
	grpc.ClientStream
}

type capletPullImageClient struct {
	grpc.ClientStream
}

func (x *capletPullImageClient) Recv() (*PullImageResponse, error) {
	m := new(PullImageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CapletServer is the server API for Caplet service.
type CapletServer interface {
	PullImage(*PullImageRequest, Caplet_PullImageServer) error
}

func RegisterCapletServer(s *grpc.Server, srv CapletServer) {
	s.RegisterService(&_Caplet_serviceDesc, srv)
}

func _Caplet_PullImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CapletServer).PullImage(m, &capletPullImageServer{stream})
}

type Caplet_PullImageServer interface {
	Send(*PullImageResponse) error
	grpc.ServerStream
}

type capletPullImageServer struct {
	grpc.ServerStream
}

func (x *capletPullImageServer) Send(m *PullImageResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Caplet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Caplet",
	HandlerType: (*CapletServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullImage",
			Handler:       _Caplet_PullImage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "caplet.proto",
}
