// Code generated by protoc-gen-go. DO NOT EDIT.
// source: captain.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InstallChartRequest struct {
	Chart                *Chart        `protobuf:"bytes,1,opt,name=chart,proto3" json:"chart,omitempty"`
	Tiller               *Tiller       `protobuf:"bytes,2,opt,name=tiller,proto3" json:"tiller,omitempty"`
	Timeout              int64         `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Pull                 bool          `protobuf:"varint,4,opt,name=pull,proto3" json:"pull,omitempty"`
	Sync                 bool          `protobuf:"varint,5,opt,name=sync,proto3" json:"sync,omitempty"`
	Retag                *ReTag        `protobuf:"bytes,6,opt,name=retag,proto3" json:"retag,omitempty"`
	RegistryAuth         *RegistryAuth `protobuf:"bytes,7,opt,name=registryAuth,proto3" json:"registryAuth,omitempty"`
	Verbose              bool          `protobuf:"varint,8,opt,name=verbose,proto3" json:"verbose,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InstallChartRequest) Reset()         { *m = InstallChartRequest{} }
func (m *InstallChartRequest) String() string { return proto.CompactTextString(m) }
func (*InstallChartRequest) ProtoMessage()    {}
func (*InstallChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f80b18f5aaa93a, []int{0}
}

func (m *InstallChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallChartRequest.Unmarshal(m, b)
}
func (m *InstallChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallChartRequest.Marshal(b, m, deterministic)
}
func (m *InstallChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallChartRequest.Merge(m, src)
}
func (m *InstallChartRequest) XXX_Size() int {
	return xxx_messageInfo_InstallChartRequest.Size(m)
}
func (m *InstallChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstallChartRequest proto.InternalMessageInfo

func (m *InstallChartRequest) GetChart() *Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *InstallChartRequest) GetTiller() *Tiller {
	if m != nil {
		return m.Tiller
	}
	return nil
}

func (m *InstallChartRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *InstallChartRequest) GetPull() bool {
	if m != nil {
		return m.Pull
	}
	return false
}

func (m *InstallChartRequest) GetSync() bool {
	if m != nil {
		return m.Sync
	}
	return false
}

func (m *InstallChartRequest) GetRetag() *ReTag {
	if m != nil {
		return m.Retag
	}
	return nil
}

func (m *InstallChartRequest) GetRegistryAuth() *RegistryAuth {
	if m != nil {
		return m.RegistryAuth
	}
	return nil
}

func (m *InstallChartRequest) GetVerbose() bool {
	if m != nil {
		return m.Verbose
	}
	return false
}

type GenerateScriptRequest struct {
	Chart                *Chart   `protobuf:"bytes,1,opt,name=chart,proto3" json:"chart,omitempty"`
	Pull                 bool     `protobuf:"varint,2,opt,name=pull,proto3" json:"pull,omitempty"`
	Retag                *ReTag   `protobuf:"bytes,3,opt,name=retag,proto3" json:"retag,omitempty"`
	Save                 bool     `protobuf:"varint,4,opt,name=save,proto3" json:"save,omitempty"`
	Load                 bool     `protobuf:"varint,5,opt,name=load,proto3" json:"load,omitempty"`
	Verbose              bool     `protobuf:"varint,6,opt,name=verbose,proto3" json:"verbose,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateScriptRequest) Reset()         { *m = GenerateScriptRequest{} }
func (m *GenerateScriptRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateScriptRequest) ProtoMessage()    {}
func (*GenerateScriptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75f80b18f5aaa93a, []int{1}
}

func (m *GenerateScriptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateScriptRequest.Unmarshal(m, b)
}
func (m *GenerateScriptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateScriptRequest.Marshal(b, m, deterministic)
}
func (m *GenerateScriptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateScriptRequest.Merge(m, src)
}
func (m *GenerateScriptRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateScriptRequest.Size(m)
}
func (m *GenerateScriptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateScriptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateScriptRequest proto.InternalMessageInfo

func (m *GenerateScriptRequest) GetChart() *Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *GenerateScriptRequest) GetPull() bool {
	if m != nil {
		return m.Pull
	}
	return false
}

func (m *GenerateScriptRequest) GetRetag() *ReTag {
	if m != nil {
		return m.Retag
	}
	return nil
}

func (m *GenerateScriptRequest) GetSave() bool {
	if m != nil {
		return m.Save
	}
	return false
}

func (m *GenerateScriptRequest) GetLoad() bool {
	if m != nil {
		return m.Load
	}
	return false
}

func (m *GenerateScriptRequest) GetVerbose() bool {
	if m != nil {
		return m.Verbose
	}
	return false
}

func init() {
	proto.RegisterType((*InstallChartRequest)(nil), "proto.InstallChartRequest")
	proto.RegisterType((*GenerateScriptRequest)(nil), "proto.GenerateScriptRequest")
}

func init() { proto.RegisterFile("captain.proto", fileDescriptor_75f80b18f5aaa93a) }

var fileDescriptor_75f80b18f5aaa93a = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x4e, 0xc2, 0x40,
	0x18, 0x74, 0xf9, 0x29, 0xb8, 0x80, 0x87, 0x25, 0x26, 0x1b, 0xe2, 0x81, 0x34, 0x31, 0xe1, 0x44,
	0x0c, 0x1e, 0x3c, 0x1b, 0x0e, 0xc4, 0x83, 0x97, 0x95, 0x17, 0x58, 0xea, 0x97, 0xd2, 0xb8, 0xb4,
	0x75, 0xf7, 0x2b, 0x09, 0x4f, 0x62, 0x7c, 0x10, 0xdf, 0xcf, 0xec, 0x4f, 0x91, 0x26, 0x70, 0xf0,
	0xd4, 0xf9, 0xe6, 0x9b, 0x76, 0x67, 0x66, 0x4b, 0x47, 0x89, 0x2c, 0x51, 0x66, 0xf9, 0xbc, 0xd4,
	0x05, 0x16, 0xac, 0xeb, 0x1e, 0x93, 0x41, 0xb2, 0x95, 0x1a, 0xe7, 0x61, 0xc8, 0x76, 0x32, 0x85,
	0x30, 0x5c, 0xef, 0x4c, 0xea, 0x61, 0xfc, 0xdd, 0xa2, 0xe3, 0x97, 0xdc, 0xa0, 0x54, 0x6a, 0x69,
	0xe5, 0x02, 0x3e, 0x2b, 0x30, 0xc8, 0x62, 0xda, 0x75, 0xaf, 0x73, 0x32, 0x25, 0xb3, 0xc1, 0x62,
	0xe8, 0xe5, 0x73, 0xaf, 0xf1, 0x2b, 0x76, 0x4f, 0x23, 0xcc, 0x94, 0x02, 0xcd, 0x5b, 0x4e, 0x34,
	0x0a, 0xa2, 0xb5, 0x23, 0x45, 0x58, 0x32, 0x4e, 0x7b, 0x98, 0xed, 0xa0, 0xa8, 0x90, 0xb7, 0xa7,
	0x64, 0xd6, 0x16, 0xf5, 0xc8, 0x18, 0xed, 0x94, 0x95, 0x52, 0xbc, 0x33, 0x25, 0xb3, 0xbe, 0x70,
	0xd8, 0x72, 0xe6, 0x90, 0x27, 0xbc, 0xeb, 0x39, 0x8b, 0xad, 0x19, 0x0d, 0x28, 0x53, 0x1e, 0x35,
	0xcc, 0x08, 0x58, 0xcb, 0x54, 0xf8, 0x15, 0x7b, 0xa2, 0x43, 0x0d, 0x69, 0x66, 0x50, 0x1f, 0x9e,
	0x2b, 0xdc, 0xf2, 0x9e, 0x93, 0x8e, 0x8f, 0xd2, 0xbf, 0x95, 0x68, 0x08, 0xad, 0xbd, 0x3d, 0xe8,
	0x4d, 0x61, 0x80, 0xf7, 0xdd, 0x99, 0xf5, 0x18, 0xff, 0x10, 0x7a, 0xbb, 0x82, 0x1c, 0xb4, 0x44,
	0x78, 0x4b, 0x74, 0x56, 0xfe, 0xab, 0x9d, 0x3a, 0x5c, 0xeb, 0x24, 0xdc, 0x31, 0x48, 0xfb, 0x72,
	0x10, 0x5b, 0x80, 0xdc, 0x43, 0x5d, 0x8a, 0xc5, 0x96, 0x53, 0x85, 0x7c, 0xaf, 0x4b, 0xb1, 0xf8,
	0xd4, 0x77, 0xd4, 0xf0, 0xbd, 0xf8, 0x22, 0xb4, 0xb7, 0xf4, 0x7f, 0x04, 0x5b, 0xd2, 0xe1, 0xe9,
	0xf5, 0xb2, 0x49, 0x38, 0xf2, 0xcc, 0x9d, 0x4f, 0xc6, 0xc7, 0x18, 0x55, 0xfe, 0xf1, 0x0a, 0xc6,
	0xc8, 0x14, 0xe2, 0xab, 0x07, 0xc2, 0x56, 0xf4, 0xa6, 0xd9, 0x03, 0xbb, 0x0b, 0xd2, 0xb3, 0xf5,
	0x5c, 0xfc, 0xd0, 0x26, 0x72, 0xfc, 0xe3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x86, 0x79, 0x5e,
	0xd5, 0xb1, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CaptainClient is the client API for Captain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CaptainClient interface {
	InstallChart(ctx context.Context, in *InstallChartRequest, opts ...grpc.CallOption) (Captain_InstallChartClient, error)
	GenerateScript(ctx context.Context, in *GenerateScriptRequest, opts ...grpc.CallOption) (Captain_GenerateScriptClient, error)
}

type captainClient struct {
	cc *grpc.ClientConn
}

func NewCaptainClient(cc *grpc.ClientConn) CaptainClient {
	return &captainClient{cc}
}

func (c *captainClient) InstallChart(ctx context.Context, in *InstallChartRequest, opts ...grpc.CallOption) (Captain_InstallChartClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Captain_serviceDesc.Streams[0], "/proto.Captain/InstallChart", opts...)
	if err != nil {
		return nil, err
	}
	x := &captainInstallChartClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Captain_InstallChartClient interface {
	Recv() (*ChunkMessage, error)
	grpc.ClientStream
}

type captainInstallChartClient struct {
	grpc.ClientStream
}

func (x *captainInstallChartClient) Recv() (*ChunkMessage, error) {
	m := new(ChunkMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *captainClient) GenerateScript(ctx context.Context, in *GenerateScriptRequest, opts ...grpc.CallOption) (Captain_GenerateScriptClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Captain_serviceDesc.Streams[1], "/proto.Captain/GenerateScript", opts...)
	if err != nil {
		return nil, err
	}
	x := &captainGenerateScriptClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Captain_GenerateScriptClient interface {
	Recv() (*ChunkMessage, error)
	grpc.ClientStream
}

type captainGenerateScriptClient struct {
	grpc.ClientStream
}

func (x *captainGenerateScriptClient) Recv() (*ChunkMessage, error) {
	m := new(ChunkMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CaptainServer is the server API for Captain service.
type CaptainServer interface {
	InstallChart(*InstallChartRequest, Captain_InstallChartServer) error
	GenerateScript(*GenerateScriptRequest, Captain_GenerateScriptServer) error
}

func RegisterCaptainServer(s *grpc.Server, srv CaptainServer) {
	s.RegisterService(&_Captain_serviceDesc, srv)
}

func _Captain_InstallChart_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InstallChartRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CaptainServer).InstallChart(m, &captainInstallChartServer{stream})
}

type Captain_InstallChartServer interface {
	Send(*ChunkMessage) error
	grpc.ServerStream
}

type captainInstallChartServer struct {
	grpc.ServerStream
}

func (x *captainInstallChartServer) Send(m *ChunkMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _Captain_GenerateScript_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateScriptRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CaptainServer).GenerateScript(m, &captainGenerateScriptServer{stream})
}

type Captain_GenerateScriptServer interface {
	Send(*ChunkMessage) error
	grpc.ServerStream
}

type captainGenerateScriptServer struct {
	grpc.ServerStream
}

func (x *captainGenerateScriptServer) Send(m *ChunkMessage) error {
	return x.ServerStream.SendMsg(m)
}

var _Captain_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Captain",
	HandlerType: (*CaptainServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InstallChart",
			Handler:       _Captain_InstallChart_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GenerateScript",
			Handler:       _Captain_GenerateScript_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "captain.proto",
}
