// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/protobuf-spec/captain.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InstallChartRequest struct {
	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Content  []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// timeout specifies the max amount of time any caplet can run.
	Timeout              int64    `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallChartRequest) Reset()         { *m = InstallChartRequest{} }
func (m *InstallChartRequest) String() string { return proto.CompactTextString(m) }
func (*InstallChartRequest) ProtoMessage()    {}
func (*InstallChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4748fcc72224947, []int{0}
}

func (m *InstallChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallChartRequest.Unmarshal(m, b)
}
func (m *InstallChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallChartRequest.Marshal(b, m, deterministic)
}
func (m *InstallChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallChartRequest.Merge(m, src)
}
func (m *InstallChartRequest) XXX_Size() int {
	return xxx_messageInfo_InstallChartRequest.Size(m)
}
func (m *InstallChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstallChartRequest proto.InternalMessageInfo

func (m *InstallChartRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *InstallChartRequest) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *InstallChartRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type InstallChartResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallChartResponse) Reset()         { *m = InstallChartResponse{} }
func (m *InstallChartResponse) String() string { return proto.CompactTextString(m) }
func (*InstallChartResponse) ProtoMessage()    {}
func (*InstallChartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4748fcc72224947, []int{1}
}

func (m *InstallChartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallChartResponse.Unmarshal(m, b)
}
func (m *InstallChartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallChartResponse.Marshal(b, m, deterministic)
}
func (m *InstallChartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallChartResponse.Merge(m, src)
}
func (m *InstallChartResponse) XXX_Size() int {
	return xxx_messageInfo_InstallChartResponse.Size(m)
}
func (m *InstallChartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallChartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstallChartResponse proto.InternalMessageInfo

func (m *InstallChartResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*InstallChartRequest)(nil), "proto.InstallChartRequest")
	proto.RegisterType((*InstallChartResponse)(nil), "proto.InstallChartResponse")
}

func init() { proto.RegisterFile("api/protobuf-spec/captain.proto", fileDescriptor_f4748fcc72224947) }

var fileDescriptor_f4748fcc72224947 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4f, 0x2c, 0xc8, 0xd4,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2d, 0x2e, 0x48, 0x4d, 0xd6, 0x4f, 0x4e,
	0x2c, 0x28, 0x49, 0xcc, 0xcc, 0xd3, 0x03, 0x8b, 0x0a, 0xb1, 0x82, 0x29, 0xa5, 0x54, 0x2e, 0x61,
	0xcf, 0xbc, 0xe2, 0x92, 0xc4, 0x9c, 0x1c, 0xe7, 0x8c, 0xc4, 0xa2, 0x92, 0xa0, 0xd4, 0xc2, 0xd2,
	0xd4, 0xe2, 0x12, 0x21, 0x29, 0x2e, 0x8e, 0xb4, 0xcc, 0x9c, 0x54, 0xbf, 0xc4, 0xdc, 0x54, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x5f, 0x48, 0x82, 0x8b, 0x3d, 0x39, 0x3f, 0xaf, 0x24,
	0x35, 0xaf, 0x44, 0x82, 0x49, 0x81, 0x51, 0x83, 0x27, 0x08, 0xc6, 0x05, 0xc9, 0x94, 0x64, 0xe6,
	0xa6, 0xe6, 0x97, 0x96, 0x48, 0x30, 0x2b, 0x30, 0x6a, 0x30, 0x07, 0xc1, 0xb8, 0x4a, 0x06, 0x5c,
	0x22, 0xa8, 0xd6, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0x83, 0xcd, 0xca, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c,
	0x87, 0x59, 0x03, 0xe3, 0x1a, 0x85, 0x70, 0xb1, 0x3b, 0x43, 0x1c, 0x2c, 0xe4, 0xc9, 0xc5, 0x83,
	0xac, 0x59, 0x48, 0x0a, 0xe2, 0x05, 0x3d, 0x2c, 0x0e, 0x97, 0x92, 0xc6, 0x2a, 0x07, 0xb1, 0x4d,
	0x89, 0x21, 0x89, 0x0d, 0x2c, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x97, 0xe3, 0x2c, 0xff,
	0x1f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CaptainClient is the client API for Captain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CaptainClient interface {
	InstallChart(ctx context.Context, in *InstallChartRequest, opts ...grpc.CallOption) (*InstallChartResponse, error)
}

type captainClient struct {
	cc *grpc.ClientConn
}

func NewCaptainClient(cc *grpc.ClientConn) CaptainClient {
	return &captainClient{cc}
}

func (c *captainClient) InstallChart(ctx context.Context, in *InstallChartRequest, opts ...grpc.CallOption) (*InstallChartResponse, error) {
	out := new(InstallChartResponse)
	err := c.cc.Invoke(ctx, "/proto.Captain/InstallChart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CaptainServer is the server API for Captain service.
type CaptainServer interface {
	InstallChart(context.Context, *InstallChartRequest) (*InstallChartResponse, error)
}

func RegisterCaptainServer(s *grpc.Server, srv CaptainServer) {
	s.RegisterService(&_Captain_serviceDesc, srv)
}

func _Captain_InstallChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptainServer).InstallChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Captain/InstallChart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptainServer).InstallChart(ctx, req.(*InstallChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Captain_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Captain",
	HandlerType: (*CaptainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstallChart",
			Handler:    _Captain_InstallChart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protobuf-spec/captain.proto",
}
