// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chart.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Chart struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	FileSize             int64    `protobuf:"varint,3,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chart) Reset()         { *m = Chart{} }
func (m *Chart) String() string { return proto.CompactTextString(m) }
func (*Chart) ProtoMessage()    {}
func (*Chart) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2b6c44db8db459e, []int{0}
}

func (m *Chart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chart.Unmarshal(m, b)
}
func (m *Chart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chart.Marshal(b, m, deterministic)
}
func (m *Chart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chart.Merge(m, src)
}
func (m *Chart) XXX_Size() int {
	return xxx_messageInfo_Chart.Size(m)
}
func (m *Chart) XXX_DiscardUnknown() {
	xxx_messageInfo_Chart.DiscardUnknown(m)
}

var xxx_messageInfo_Chart proto.InternalMessageInfo

func (m *Chart) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *Chart) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Chart) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

// Tiller is the Helm Server
type Tiller struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	SkipSslValidation    bool     `protobuf:"varint,5,opt,name=skipSslValidation,proto3" json:"skipSslValidation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tiller) Reset()         { *m = Tiller{} }
func (m *Tiller) String() string { return proto.CompactTextString(m) }
func (*Tiller) ProtoMessage()    {}
func (*Tiller) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2b6c44db8db459e, []int{1}
}

func (m *Tiller) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tiller.Unmarshal(m, b)
}
func (m *Tiller) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tiller.Marshal(b, m, deterministic)
}
func (m *Tiller) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tiller.Merge(m, src)
}
func (m *Tiller) XXX_Size() int {
	return xxx_messageInfo_Tiller.Size(m)
}
func (m *Tiller) XXX_DiscardUnknown() {
	xxx_messageInfo_Tiller.DiscardUnknown(m)
}

var xxx_messageInfo_Tiller proto.InternalMessageInfo

func (m *Tiller) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Tiller) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Tiller) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Tiller) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Tiller) GetSkipSslValidation() bool {
	if m != nil {
		return m.SkipSslValidation
	}
	return false
}

func init() {
	proto.RegisterType((*Chart)(nil), "proto.Chart")
	proto.RegisterType((*Tiller)(nil), "proto.Tiller")
}

func init() { proto.RegisterFile("chart.proto", fileDescriptor_b2b6c44db8db459e) }

var fileDescriptor_b2b6c44db8db459e = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x31, 0x8f, 0xc2, 0x20,
	0x14, 0xc7, 0x43, 0x7b, 0xed, 0xb5, 0xdc, 0x2d, 0xc7, 0x44, 0x6e, 0x22, 0x9d, 0x18, 0x8c, 0x8b,
	0x1f, 0xc1, 0xdd, 0x81, 0x1a, 0x13, 0x47, 0xa4, 0x18, 0x89, 0x08, 0x04, 0x68, 0x4c, 0xfc, 0x3c,
	0x7e, 0x50, 0x03, 0x86, 0x2e, 0x4e, 0xe4, 0xc7, 0xef, 0xbd, 0xff, 0x7b, 0x79, 0xf0, 0x47, 0x5c,
	0xb8, 0x8f, 0x6b, 0xe7, 0x6d, 0xb4, 0xa8, 0xc9, 0xcf, 0x70, 0x84, 0xcd, 0x36, 0xfd, 0xa2, 0x7f,
	0xd8, 0x9d, 0x95, 0x96, 0x3b, 0x7e, 0x93, 0x18, 0x10, 0x40, 0x7b, 0xb6, 0x30, 0xc2, 0xf0, 0x5b,
	0x58, 0x13, 0xa5, 0x89, 0xb8, 0x22, 0x80, 0xfe, 0xb2, 0x82, 0xa5, 0x6b, 0x54, 0x0f, 0x89, 0x6b,
	0x02, 0x68, 0xcd, 0x16, 0x1e, 0x9e, 0x00, 0xb6, 0x7b, 0xa5, 0xb5, 0xf4, 0xa9, 0x4c, 0x9a, 0xc9,
	0x59, 0x65, 0x62, 0x09, 0x2f, 0x9c, 0xdc, 0x1c, 0xa4, 0x37, 0x69, 0x70, 0xf5, 0x76, 0x85, 0x93,
	0x73, 0x3c, 0x84, 0xbb, 0xf5, 0x53, 0x8e, 0xef, 0xd9, 0xc2, 0x69, 0x29, 0x2e, 0x84, 0x9d, 0x4d,
	0xc4, 0x5f, 0x59, 0x15, 0x44, 0x2b, 0xf8, 0x17, 0xae, 0xca, 0x8d, 0x41, 0x1f, 0xb8, 0x56, 0x13,
	0x8f, 0xca, 0x1a, 0xdc, 0x10, 0x40, 0x3b, 0xf6, 0x29, 0x4e, 0x6d, 0x3e, 0xc4, 0xe6, 0x15, 0x00,
	0x00, 0xff, 0xff, 0xd1, 0x65, 0x80, 0x71, 0x1e, 0x01, 0x00, 0x00,
}
