// Code generated by protoc-gen-go. DO NOT EDIT.
// source: console_url.proto

// 依照 https://cloud.google.com/apis/design/naming_convention 規範

package captainkube_v2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConsoleURLRequest struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsoleURLRequest) Reset()         { *m = ConsoleURLRequest{} }
func (m *ConsoleURLRequest) String() string { return proto.CompactTextString(m) }
func (*ConsoleURLRequest) ProtoMessage()    {}
func (*ConsoleURLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fa6ccda9672d7cf, []int{0}
}

func (m *ConsoleURLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsoleURLRequest.Unmarshal(m, b)
}
func (m *ConsoleURLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsoleURLRequest.Marshal(b, m, deterministic)
}
func (m *ConsoleURLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsoleURLRequest.Merge(m, src)
}
func (m *ConsoleURLRequest) XXX_Size() int {
	return xxx_messageInfo_ConsoleURLRequest.Size(m)
}
func (m *ConsoleURLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsoleURLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConsoleURLRequest proto.InternalMessageInfo

func (m *ConsoleURLRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type ConsoleURLResponse struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsoleURLResponse) Reset()         { *m = ConsoleURLResponse{} }
func (m *ConsoleURLResponse) String() string { return proto.CompactTextString(m) }
func (*ConsoleURLResponse) ProtoMessage()    {}
func (*ConsoleURLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fa6ccda9672d7cf, []int{1}
}

func (m *ConsoleURLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsoleURLResponse.Unmarshal(m, b)
}
func (m *ConsoleURLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsoleURLResponse.Marshal(b, m, deterministic)
}
func (m *ConsoleURLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsoleURLResponse.Merge(m, src)
}
func (m *ConsoleURLResponse) XXX_Size() int {
	return xxx_messageInfo_ConsoleURLResponse.Size(m)
}
func (m *ConsoleURLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsoleURLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConsoleURLResponse proto.InternalMessageInfo

func (m *ConsoleURLResponse) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *ConsoleURLResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*ConsoleURLRequest)(nil), "softleader.captainkube.v2.ConsoleURLRequest")
	proto.RegisterType((*ConsoleURLResponse)(nil), "softleader.captainkube.v2.ConsoleURLResponse")
}

func init() { proto.RegisterFile("console_url.proto", fileDescriptor_2fa6ccda9672d7cf) }

var fileDescriptor_2fa6ccda9672d7cf = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0xce, 0xcf, 0x2b,
	0xce, 0xcf, 0x49, 0x8d, 0x2f, 0x2d, 0xca, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x2c,
	0xce, 0x4f, 0x2b, 0xc9, 0x49, 0x4d, 0x4c, 0x49, 0x2d, 0xd2, 0x4b, 0x4e, 0x2c, 0x28, 0x49, 0xcc,
	0xcc, 0xcb, 0x2e, 0x4d, 0x4a, 0xd5, 0x2b, 0x33, 0x52, 0x52, 0xe7, 0x12, 0x74, 0x86, 0xa8, 0x0f,
	0x0d, 0xf2, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0xc8, 0x2f,
	0x2e, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0xec, 0xb8, 0x84, 0x90, 0x15,
	0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x89, 0x71, 0xb1, 0x95, 0xa5, 0xe6, 0xa5, 0xe4, 0x17,
	0x41, 0xd5, 0x42, 0x79, 0x42, 0x02, 0x5c, 0xcc, 0xa5, 0x45, 0x39, 0x12, 0x4c, 0x60, 0x41, 0x10,
	0xd3, 0xc9, 0x88, 0x4b, 0xa1, 0xa4, 0x5c, 0x2f, 0x39, 0x3f, 0x57, 0x0f, 0xa7, 0x63, 0xa2, 0xf8,
	0x50, 0xf9, 0x49, 0x6c, 0x60, 0xe7, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x83, 0x9e, 0x75,
	0x36, 0xd3, 0x00, 0x00, 0x00,
}
