// Code generated by protoc-gen-go. DO NOT EDIT.
// source: image.proto

// 依照 https://cloud.google.com/apis/design/naming_convention 規範

package captainkube_v2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Image struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Repo                 string   `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_9624c68e2b547544, []int{0}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Image) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *Image) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type ReTag struct {
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReTag) Reset()         { *m = ReTag{} }
func (m *ReTag) String() string { return proto.CompactTextString(m) }
func (*ReTag) ProtoMessage()    {}
func (*ReTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_9624c68e2b547544, []int{1}
}

func (m *ReTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReTag.Unmarshal(m, b)
}
func (m *ReTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReTag.Marshal(b, m, deterministic)
}
func (m *ReTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReTag.Merge(m, src)
}
func (m *ReTag) XXX_Size() int {
	return xxx_messageInfo_ReTag.Size(m)
}
func (m *ReTag) XXX_DiscardUnknown() {
	xxx_messageInfo_ReTag.DiscardUnknown(m)
}

var xxx_messageInfo_ReTag proto.InternalMessageInfo

func (m *ReTag) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ReTag) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type RegistryAuth struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistryAuth) Reset()         { *m = RegistryAuth{} }
func (m *RegistryAuth) String() string { return proto.CompactTextString(m) }
func (*RegistryAuth) ProtoMessage()    {}
func (*RegistryAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_9624c68e2b547544, []int{2}
}

func (m *RegistryAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistryAuth.Unmarshal(m, b)
}
func (m *RegistryAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistryAuth.Marshal(b, m, deterministic)
}
func (m *RegistryAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistryAuth.Merge(m, src)
}
func (m *RegistryAuth) XXX_Size() int {
	return xxx_messageInfo_RegistryAuth.Size(m)
}
func (m *RegistryAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistryAuth.DiscardUnknown(m)
}

var xxx_messageInfo_RegistryAuth proto.InternalMessageInfo

func (m *RegistryAuth) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegistryAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Image)(nil), "softleader.captainkube.v2.Image")
	proto.RegisterType((*ReTag)(nil), "softleader.captainkube.v2.ReTag")
	proto.RegisterType((*RegistryAuth)(nil), "softleader.captainkube.v2.RegistryAuth")
}

func init() { proto.RegisterFile("image.proto", fileDescriptor_9624c68e2b547544) }

var fileDescriptor_9624c68e2b547544 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0x86, 0x40,
	0x10, 0x86, 0xf9, 0xfc, 0x32, 0x6a, 0x0a, 0x89, 0x3d, 0x59, 0x27, 0xf1, 0x14, 0x04, 0x7b, 0xb0,
	0x5f, 0x60, 0x87, 0xa0, 0x5b, 0x48, 0x5d, 0xba, 0x8d, 0x3a, 0xae, 0x52, 0xeb, 0xc8, 0xee, 0x98,
	0xf4, 0xef, 0x63, 0xcd, 0x84, 0x0e, 0xdd, 0x9e, 0xf7, 0xdd, 0x87, 0x1d, 0x66, 0xe0, 0x62, 0xb0,
	0x68, 0x48, 0x4f, 0x8e, 0x85, 0xd5, 0xb5, 0xe7, 0x4e, 0x3e, 0x08, 0x5b, 0x72, 0xba, 0xc1, 0x49,
	0x70, 0x18, 0xdf, 0xe7, 0x9a, 0xf4, 0x67, 0x91, 0x97, 0x10, 0x3f, 0x05, 0x53, 0x29, 0x38, 0xe9,
	0xd9, 0x4b, 0x7a, 0xc8, 0x0e, 0xb7, 0xe7, 0xd5, 0xca, 0xa1, 0x73, 0x34, 0x71, 0x1a, 0xfd, 0x74,
	0x81, 0xd5, 0x15, 0x1c, 0x05, 0x4d, 0x7a, 0x5c, 0xab, 0x80, 0xf9, 0x1d, 0xc4, 0x15, 0xbd, 0xa0,
	0x09, 0x7a, 0xe7, 0xd8, 0xfe, 0xea, 0x81, 0x55, 0x02, 0x91, 0xf0, 0x66, 0x47, 0xc2, 0xf9, 0x23,
	0x5c, 0x56, 0x64, 0x06, 0x2f, 0xee, 0xab, 0x9c, 0xa5, 0x57, 0x37, 0x70, 0xf6, 0xea, 0xc9, 0x8d,
	0x68, 0x69, 0x1b, 0xbd, 0xe7, 0xf0, 0xf6, 0x8c, 0xde, 0x2f, 0xec, 0xda, 0xed, 0xcf, 0x3d, 0x3f,
	0x14, 0x90, 0xc9, 0xa2, 0x1b, 0xb6, 0xfa, 0xdf, 0xdd, 0xde, 0x92, 0xbf, 0xb9, 0x3e, 0x5d, 0xaf,
	0x71, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xff, 0xba, 0x48, 0xbd, 0x1c, 0x01, 0x00, 0x00,
}
