// Code generated by protoc-gen-go. DO NOT EDIT.
// source: k8s.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type K8SVendor int32

const (
	K8SVendor_Gcp K8SVendor = 0
	K8SVendor_Icp K8SVendor = 1
)

var K8SVendor_name = map[int32]string{
	0: "Gcp",
	1: "Icp",
}

var K8SVendor_value = map[string]int32{
	"Gcp": 0,
	"Icp": 1,
}

func (x K8SVendor) String() string {
	return proto.EnumName(K8SVendor_name, int32(x))
}

func (K8SVendor) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e25cbc1b2df348ba, []int{0}
}

type K8S struct {
	Vendor               K8SVendor `protobuf:"varint,1,opt,name=vendor,proto3,enum=proto.K8SVendor" json:"vendor,omitempty"`
	Endpoint             string    `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *K8S) Reset()         { *m = K8S{} }
func (m *K8S) String() string { return proto.CompactTextString(m) }
func (*K8S) ProtoMessage()    {}
func (*K8S) Descriptor() ([]byte, []int) {
	return fileDescriptor_e25cbc1b2df348ba, []int{0}
}

func (m *K8S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_K8S.Unmarshal(m, b)
}
func (m *K8S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_K8S.Marshal(b, m, deterministic)
}
func (m *K8S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_K8S.Merge(m, src)
}
func (m *K8S) XXX_Size() int {
	return xxx_messageInfo_K8S.Size(m)
}
func (m *K8S) XXX_DiscardUnknown() {
	xxx_messageInfo_K8S.DiscardUnknown(m)
}

var xxx_messageInfo_K8S proto.InternalMessageInfo

func (m *K8S) GetVendor() K8SVendor {
	if m != nil {
		return m.Vendor
	}
	return K8SVendor_Gcp
}

func (m *K8S) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.K8SVendor", K8SVendor_name, K8SVendor_value)
	proto.RegisterType((*K8S)(nil), "proto.K8s")
}

func init() { proto.RegisterFile("k8s.proto", fileDescriptor_e25cbc1b2df348ba) }

var fileDescriptor_e25cbc1b2df348ba = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0xb6, 0x28, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xde, 0x5c, 0xcc, 0xde, 0x16, 0xc5,
	0x42, 0x1a, 0x5c, 0x6c, 0x65, 0xa9, 0x79, 0x29, 0xf9, 0x45, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x7c,
	0x46, 0x02, 0x10, 0x55, 0x7a, 0xde, 0x16, 0xc5, 0x61, 0x60, 0xf1, 0x20, 0xa8, 0xbc, 0x90, 0x14,
	0x17, 0x47, 0x6a, 0x5e, 0x4a, 0x41, 0x7e, 0x66, 0x5e, 0x89, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67,
	0x10, 0x9c, 0xaf, 0x25, 0xcb, 0xc5, 0x09, 0xd7, 0x20, 0xc4, 0xce, 0xc5, 0xec, 0x9e, 0x5c, 0x20,
	0xc0, 0x00, 0x62, 0x78, 0x26, 0x17, 0x08, 0x30, 0x26, 0xb1, 0x81, 0xcd, 0x34, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x97, 0x89, 0x23, 0x56, 0x86, 0x00, 0x00, 0x00,
}
