// Code generated by protoc-gen-go. DO NOT EDIT.
// source: k8s.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Icp struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Icp) Reset()         { *m = Icp{} }
func (m *Icp) String() string { return proto.CompactTextString(m) }
func (*Icp) ProtoMessage()    {}
func (*Icp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e25cbc1b2df348ba, []int{0}
}

func (m *Icp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Icp.Unmarshal(m, b)
}
func (m *Icp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Icp.Marshal(b, m, deterministic)
}
func (m *Icp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Icp.Merge(m, src)
}
func (m *Icp) XXX_Size() int {
	return xxx_messageInfo_Icp.Size(m)
}
func (m *Icp) XXX_DiscardUnknown() {
	xxx_messageInfo_Icp.DiscardUnknown(m)
}

var xxx_messageInfo_Icp proto.InternalMessageInfo

func (m *Icp) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

type Gcp struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gcp) Reset()         { *m = Gcp{} }
func (m *Gcp) String() string { return proto.CompactTextString(m) }
func (*Gcp) ProtoMessage()    {}
func (*Gcp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e25cbc1b2df348ba, []int{1}
}

func (m *Gcp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gcp.Unmarshal(m, b)
}
func (m *Gcp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gcp.Marshal(b, m, deterministic)
}
func (m *Gcp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gcp.Merge(m, src)
}
func (m *Gcp) XXX_Size() int {
	return xxx_messageInfo_Gcp.Size(m)
}
func (m *Gcp) XXX_DiscardUnknown() {
	xxx_messageInfo_Gcp.DiscardUnknown(m)
}

var xxx_messageInfo_Gcp proto.InternalMessageInfo

func (m *Gcp) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func init() {
	proto.RegisterType((*Icp)(nil), "proto.Icp")
	proto.RegisterType((*Gcp)(nil), "proto.Gcp")
}

func init() { proto.RegisterFile("k8s.proto", fileDescriptor_e25cbc1b2df348ba) }

var fileDescriptor_e25cbc1b2df348ba = []byte{
	// 77 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0xb6, 0x28, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x8a, 0x5c, 0xcc, 0x9e, 0xc9, 0x05,
	0x42, 0x52, 0x5c, 0x1c, 0xa9, 0x79, 0x29, 0x05, 0xf9, 0x99, 0x79, 0x25, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x70, 0x3e, 0x48, 0x89, 0x3b, 0x7e, 0x25, 0x49, 0x6c, 0x60, 0xc3, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x22, 0xfd, 0x03, 0x8f, 0x60, 0x00, 0x00, 0x00,
}
