// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChunkMessage struct {
	Msg                  []byte   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChunkMessage) Reset()         { *m = ChunkMessage{} }
func (m *ChunkMessage) String() string { return proto.CompactTextString(m) }
func (*ChunkMessage) ProtoMessage()    {}
func (*ChunkMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *ChunkMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChunkMessage.Unmarshal(m, b)
}
func (m *ChunkMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChunkMessage.Marshal(b, m, deterministic)
}
func (m *ChunkMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChunkMessage.Merge(m, src)
}
func (m *ChunkMessage) XXX_Size() int {
	return xxx_messageInfo_ChunkMessage.Size(m)
}
func (m *ChunkMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChunkMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChunkMessage proto.InternalMessageInfo

func (m *ChunkMessage) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*ChunkMessage)(nil), "proto.ChunkMessage")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 75 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x0a, 0x5c, 0x3c, 0xce, 0x19, 0xa5,
	0x79, 0xd9, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x42, 0x02, 0x5c, 0xcc, 0xb9, 0xc5, 0xe9,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x20, 0x66, 0x12, 0x1b, 0x58, 0xa1, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xc4, 0xdf, 0xbe, 0xaa, 0x3c, 0x00, 0x00, 0x00,
}
