// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prune.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PruneRequest struct {
	Verbose              bool     `protobuf:"varint,1,opt,name=verbose,proto3" json:"verbose,omitempty"`
	Timeout              int64    `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PruneRequest) Reset()         { *m = PruneRequest{} }
func (m *PruneRequest) String() string { return proto.CompactTextString(m) }
func (*PruneRequest) ProtoMessage()    {}
func (*PruneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04bbcb796922f3fc, []int{0}
}

func (m *PruneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PruneRequest.Unmarshal(m, b)
}
func (m *PruneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PruneRequest.Marshal(b, m, deterministic)
}
func (m *PruneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PruneRequest.Merge(m, src)
}
func (m *PruneRequest) XXX_Size() int {
	return xxx_messageInfo_PruneRequest.Size(m)
}
func (m *PruneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PruneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PruneRequest proto.InternalMessageInfo

func (m *PruneRequest) GetVerbose() bool {
	if m != nil {
		return m.Verbose
	}
	return false
}

func (m *PruneRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func init() {
	proto.RegisterType((*PruneRequest)(nil), "proto.PruneRequest")
}

func init() { proto.RegisterFile("prune.proto", fileDescriptor_04bbcb796922f3fc) }

var fileDescriptor_04bbcb796922f3fc = []byte{
	// 97 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0x2a, 0xcd,
	0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x4e, 0x5c, 0x3c, 0x01,
	0x20, 0xd1, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x09, 0x2e, 0xf6, 0xb2, 0xd4, 0xa2,
	0xa4, 0xfc, 0xe2, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x18, 0x17, 0x24, 0x53, 0x92,
	0x99, 0x9b, 0x9a, 0x5f, 0x5a, 0x22, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1c, 0x04, 0xe3, 0x26, 0xb1,
	0x81, 0x8d, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x92, 0xda, 0xc4, 0x60, 0x00, 0x00,
	0x00,
}
