// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegistryAuth struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistryAuth) Reset()         { *m = RegistryAuth{} }
func (m *RegistryAuth) String() string { return proto.CompactTextString(m) }
func (*RegistryAuth) ProtoMessage()    {}
func (*RegistryAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{0}
}

func (m *RegistryAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistryAuth.Unmarshal(m, b)
}
func (m *RegistryAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistryAuth.Marshal(b, m, deterministic)
}
func (m *RegistryAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistryAuth.Merge(m, src)
}
func (m *RegistryAuth) XXX_Size() int {
	return xxx_messageInfo_RegistryAuth.Size(m)
}
func (m *RegistryAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistryAuth.DiscardUnknown(m)
}

var xxx_messageInfo_RegistryAuth proto.InternalMessageInfo

func (m *RegistryAuth) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegistryAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*RegistryAuth)(nil), "proto.RegistryAuth")
}

func init() { proto.RegisterFile("registry.proto", fileDescriptor_41af05d40a615591) }

var fileDescriptor_41af05d40a615591 = []byte{
	// 96 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x4d, 0xcf,
	0x2c, 0x2e, 0x29, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x6e,
	0x5c, 0x3c, 0x41, 0x50, 0x09, 0xc7, 0xd2, 0x92, 0x0c, 0x21, 0x29, 0x2e, 0x8e, 0xd0, 0xe2, 0xd4,
	0xa2, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x1f, 0x24, 0x17,
	0x90, 0x58, 0x5c, 0x5c, 0x9e, 0x5f, 0x94, 0x22, 0xc1, 0x04, 0x91, 0x83, 0xf1, 0x93, 0xd8, 0xc0,
	0xc6, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x21, 0xf4, 0x11, 0x07, 0x67, 0x00, 0x00, 0x00,
}
