// Code generated by protoc-gen-go. DO NOT EDIT.
// source: retag.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Retag struct {
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Retag) Reset()         { *m = Retag{} }
func (m *Retag) String() string { return proto.CompactTextString(m) }
func (*Retag) ProtoMessage()    {}
func (*Retag) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcd84e9f4113ddcc, []int{0}
}

func (m *Retag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Retag.Unmarshal(m, b)
}
func (m *Retag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Retag.Marshal(b, m, deterministic)
}
func (m *Retag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Retag.Merge(m, src)
}
func (m *Retag) XXX_Size() int {
	return xxx_messageInfo_Retag.Size(m)
}
func (m *Retag) XXX_DiscardUnknown() {
	xxx_messageInfo_Retag.DiscardUnknown(m)
}

var xxx_messageInfo_Retag proto.InternalMessageInfo

func (m *Retag) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Retag) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func init() {
	proto.RegisterType((*Retag)(nil), "proto.Retag")
}

func init() { proto.RegisterFile("retag.proto", fileDescriptor_bcd84e9f4113ddcc) }

var fileDescriptor_bcd84e9f4113ddcc = []byte{
	// 82 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x4a, 0x2d, 0x49,
	0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xda, 0x5c, 0xac, 0x41,
	0x20, 0x51, 0x21, 0x21, 0x2e, 0x96, 0xb4, 0xa2, 0xfc, 0x5c, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce,
	0x20, 0x30, 0x5b, 0x88, 0x8f, 0x8b, 0xa9, 0x24, 0x5f, 0x82, 0x19, 0x2c, 0xc2, 0x54, 0x92, 0x9f,
	0xc4, 0x06, 0xd6, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x2a, 0x73, 0x5f, 0x49, 0x00,
	0x00, 0x00,
}
