// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rmc.proto

// 依照 https://cloud.google.com/apis/design/naming_convention 規範

package captainkube_v2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RmcRequest struct {
	Chart                *Chart   `protobuf:"bytes,1,opt,name=chart,proto3" json:"chart,omitempty"`
	Set                  []string `protobuf:"bytes,2,rep,name=set,proto3" json:"set,omitempty"`
	Range                string   `protobuf:"bytes,3,opt,name=range,proto3" json:"range,omitempty"`
	Verbose              bool     `protobuf:"varint,4,opt,name=verbose,proto3" json:"verbose,omitempty"`
	Timeout              int64    `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Color                bool     `protobuf:"varint,6,opt,name=color,proto3" json:"color,omitempty"`
	Force                bool     `protobuf:"varint,7,opt,name=force,proto3" json:"force,omitempty"`
	DryRun               bool     `protobuf:"varint,8,opt,name=dryRun,proto3" json:"dryRun,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RmcRequest) Reset()         { *m = RmcRequest{} }
func (m *RmcRequest) String() string { return proto.CompactTextString(m) }
func (*RmcRequest) ProtoMessage()    {}
func (*RmcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35e41f379f3a71cc, []int{0}
}

func (m *RmcRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmcRequest.Unmarshal(m, b)
}
func (m *RmcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmcRequest.Marshal(b, m, deterministic)
}
func (m *RmcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmcRequest.Merge(m, src)
}
func (m *RmcRequest) XXX_Size() int {
	return xxx_messageInfo_RmcRequest.Size(m)
}
func (m *RmcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RmcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RmcRequest proto.InternalMessageInfo

func (m *RmcRequest) GetChart() *Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *RmcRequest) GetSet() []string {
	if m != nil {
		return m.Set
	}
	return nil
}

func (m *RmcRequest) GetRange() string {
	if m != nil {
		return m.Range
	}
	return ""
}

func (m *RmcRequest) GetVerbose() bool {
	if m != nil {
		return m.Verbose
	}
	return false
}

func (m *RmcRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *RmcRequest) GetColor() bool {
	if m != nil {
		return m.Color
	}
	return false
}

func (m *RmcRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

func (m *RmcRequest) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

func init() {
	proto.RegisterType((*RmcRequest)(nil), "softleader.captainkube.v2.RmcRequest")
}

func init() { proto.RegisterFile("rmc.proto", fileDescriptor_35e41f379f3a71cc) }

var fileDescriptor_35e41f379f3a71cc = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x65, 0x42, 0xd2, 0xc6, 0x95, 0x10, 0xb2, 0x10, 0x32, 0x4c, 0x16, 0x93, 0x27, 0x0f,
	0x41, 0xe2, 0x01, 0xe0, 0x0d, 0x3c, 0xb2, 0x39, 0xee, 0x15, 0x2a, 0x9a, 0x5c, 0xb9, 0x5c, 0x8a,
	0x78, 0x5f, 0x1e, 0x04, 0xd9, 0xa6, 0x03, 0x43, 0xb6, 0xfb, 0xfe, 0xff, 0xbf, 0x5f, 0xba, 0x93,
	0x2d, 0x0d, 0xd1, 0x1d, 0x09, 0x19, 0xd5, 0xdd, 0x84, 0x3b, 0x3e, 0x40, 0xd8, 0x02, 0xb9, 0x18,
	0x8e, 0x1c, 0xf6, 0xe3, 0xc7, 0xdc, 0x83, 0x3b, 0x75, 0xf7, 0x9b, 0xf8, 0x1e, 0x88, 0x4b, 0xee,
	0xe1, 0x47, 0x48, 0xe9, 0x87, 0xe8, 0xe1, 0x73, 0x86, 0x89, 0xd5, 0x93, 0xac, 0xb3, 0xab, 0x85,
	0x11, 0x76, 0xd3, 0x19, 0xb7, 0x58, 0xe3, 0x5e, 0x52, 0xce, 0x97, 0xb8, 0xba, 0x96, 0xd5, 0x04,
	0xac, 0x2f, 0x4c, 0x65, 0x5b, 0x9f, 0x46, 0x75, 0x23, 0x6b, 0x0a, 0xe3, 0x1b, 0xe8, 0xca, 0x08,
	0xdb, 0xfa, 0x02, 0x4a, 0xcb, 0xd5, 0x09, 0xa8, 0xc7, 0x09, 0xf4, 0xa5, 0x11, 0x76, 0xed, 0xcf,
	0x98, 0x1c, 0xde, 0x0f, 0x80, 0x33, 0xeb, 0xda, 0x08, 0x5b, 0xf9, 0x33, 0xa6, 0xa6, 0x88, 0x07,
	0x24, 0xdd, 0xe4, 0x8d, 0x02, 0x49, 0xdd, 0x21, 0x45, 0xd0, 0xab, 0xa2, 0x66, 0x50, 0xb7, 0xb2,
	0xd9, 0xd2, 0xb7, 0x9f, 0x47, 0xbd, 0xce, 0xf2, 0x1f, 0x3d, 0x77, 0xd2, 0xf0, 0x97, 0x8b, 0x38,
	0x2c, 0x1f, 0xf4, 0x7a, 0xf5, 0x9f, 0xfb, 0x26, 0x7f, 0xe8, 0xf1, 0x37, 0x00, 0x00, 0xff, 0xff,
	0xa7, 0x76, 0xe6, 0xe8, 0x56, 0x01, 0x00, 0x00,
}
