// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rmi.proto

// 依照 https://cloud.google.com/apis/design/naming_convention 規範

package captainkube_v2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RmiRequest struct {
	Images               []*Image `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	Verbose              bool     `protobuf:"varint,3,opt,name=verbose,proto3" json:"verbose,omitempty"`
	Timeout              string   `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Color                bool     `protobuf:"varint,5,opt,name=color,proto3" json:"color,omitempty"`
	Force                bool     `protobuf:"varint,6,opt,name=force,proto3" json:"force,omitempty"`
	DryRun               bool     `protobuf:"varint,7,opt,name=dryRun,proto3" json:"dryRun,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RmiRequest) Reset()         { *m = RmiRequest{} }
func (m *RmiRequest) String() string { return proto.CompactTextString(m) }
func (*RmiRequest) ProtoMessage()    {}
func (*RmiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_581e02de60ed53de, []int{0}
}

func (m *RmiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmiRequest.Unmarshal(m, b)
}
func (m *RmiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmiRequest.Marshal(b, m, deterministic)
}
func (m *RmiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmiRequest.Merge(m, src)
}
func (m *RmiRequest) XXX_Size() int {
	return xxx_messageInfo_RmiRequest.Size(m)
}
func (m *RmiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RmiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RmiRequest proto.InternalMessageInfo

func (m *RmiRequest) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *RmiRequest) GetVerbose() bool {
	if m != nil {
		return m.Verbose
	}
	return false
}

func (m *RmiRequest) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

func (m *RmiRequest) GetColor() bool {
	if m != nil {
		return m.Color
	}
	return false
}

func (m *RmiRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

func (m *RmiRequest) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

func init() {
	proto.RegisterType((*RmiRequest)(nil), "softleader.captainkube.v2.RmiRequest")
}

func init() { proto.RegisterFile("rmi.proto", fileDescriptor_581e02de60ed53de) }

var fileDescriptor_581e02de60ed53de = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0x65, 0x95, 0xba, 0xf4, 0x2a, 0x31, 0x58, 0x08, 0x19, 0x26, 0x8b, 0x29, 0x93, 0x87,
	0xb0, 0x30, 0xb3, 0xb1, 0x7a, 0x64, 0x73, 0xdc, 0x2b, 0xb2, 0xa8, 0x7b, 0xc1, 0x1f, 0x41, 0xfc,
	0x39, 0x7e, 0x1b, 0x8a, 0x93, 0x0c, 0x1d, 0x32, 0x3e, 0xef, 0xfb, 0xdc, 0xe9, 0x0e, 0xf6, 0x31,
	0x78, 0xdd, 0x47, 0xca, 0x24, 0x1e, 0x13, 0x9d, 0xf2, 0x19, 0xed, 0x11, 0xa3, 0x76, 0xb6, 0xcf,
	0xd6, 0x5f, 0xbe, 0x4a, 0x87, 0x7a, 0x68, 0x9f, 0x0e, 0x3e, 0xd8, 0x4f, 0x9c, 0xbc, 0xe7, 0x3f,
	0x06, 0x60, 0x82, 0x37, 0xf8, 0x5d, 0x30, 0x65, 0xf1, 0x0a, 0xbc, 0xb6, 0x49, 0x32, 0xb5, 0x69,
	0x0e, 0xad, 0xd2, 0xab, 0x7b, 0xf4, 0xfb, 0x28, 0x9a, 0xd9, 0x17, 0x12, 0x76, 0x03, 0xc6, 0x8e,
	0x12, 0xca, 0x8d, 0x62, 0xcd, 0xad, 0x59, 0x70, 0x6c, 0xb2, 0x0f, 0x48, 0x25, 0xcb, 0x1b, 0xc5,
	0x9a, 0xbd, 0x59, 0x50, 0xdc, 0xc3, 0xd6, 0xd1, 0x99, 0xa2, 0xdc, 0xd6, 0x89, 0x09, 0xc6, 0xf4,
	0x44, 0xd1, 0xa1, 0xe4, 0x53, 0x5a, 0x41, 0x3c, 0x00, 0x3f, 0xc6, 0x5f, 0x53, 0x2e, 0x72, 0x57,
	0xe3, 0x99, 0xde, 0x5a, 0x50, 0xf9, 0x47, 0x3b, 0x0a, 0xeb, 0x97, 0x7e, 0xdc, 0x5d, 0x73, 0xc7,
	0xeb, 0xef, 0x2f, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xc2, 0xf2, 0xc8, 0x30, 0x01, 0x00,
	0x00,
}
