---
- name: Uploading chart
  copy:
    src: "{{ chart_path }}"
    dest: "{{ workdir.path }}/{{ chart }}"
  when: labels is defined and "master" in labels
  tags:
    - always

- name: Login bx pr
  shell: bx pr login -a https://{{ inventory_hostname }}:8443 --skip-ssl-validation -u {{ kubectl_user }} -p '{{ kubectl_pass }}' -c '{{ icp_account }}'
  when: labels is defined and "master" in labels
  tags:
    - icp

- name: Loading chart
  shell: bx pr load-helm-chart --archive {{ workdir.path }}/{{ chart }}
  when: labels is defined and "master" in labels
  tags:
    - icp

- name: Installing chart
  shell: helm install {{ workdir.path }}/{{ chart }} -n {{ namespace }}
  when: labels is defined and "master" in labels
  tags:
    - helm